NUMPY


In [8]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy

In [10]:
a=numpy.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
type(a)

numpy.ndarray

In [15]:
 a=numpy.array([[1,2,3,4]])
print(a)


[[1 2 3 4]]


In [16]:
print(a.ndim)

2


In [19]:
a=numpy.array([[[1,2,3,4]]])
print(a)

[[[1 2 3 4]]]


In [20]:
print(a.ndim)

3


In [21]:
a=numpy.array([[[[1,2,3,4]]]])
print(a)

[[[[1 2 3 4]]]]


In [22]:
print(a.ndim)

4


In [23]:
a=numpy.array([[[[[[[1,2,3,4]]]]]]])
print(a)

[[[[[[[1 2 3 4]]]]]]]


In [24]:
print(a.ndim)


7


In [32]:
a=numpy.array([1,2,3,4],ndmin=4)
print(a)


[[[[1 2 3 4]]]]


In [35]:
a=numpy.array([[1,2,3,4,5]],ndmin=3)
print(a)

[[[1 2 3 4 5]]]


In [3]:
a=[1,2,3]

In [4]:
a[2]

3

In [38]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[1,1])

5


In [39]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [27]:
a

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [47]:
print(a[0,1,0])

4


In [48]:
print(a.shape)

(2, 2, 3)


In [50]:
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [52]:
a=np.array([[1,2,3],[4,5,6]])

In [53]:
print(a.ndim)

2


In [54]:
print(a.shape)

(2, 3)


In [55]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [56]:
print(a.ndim)

3


In [57]:
print(a.shape)

(2, 2, 3)


In [60]:
a.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [61]:
a=np.array([[1,2,3],[4,5,6]])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
print(a.shape)

(2, 3)


In [70]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
a=[1:2]

SyntaxError: invalid syntax (3116054557.py, line 1)

In [74]:
a=[1,2,3,4,5,6]

In [77]:
a[2:5]

[3, 4, 5]

In [98]:
a=np.array([[1,2,3],[4,5,6]])

In [79]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
print(a[0:2,1:2])

[[2]
 [5]]


In [101]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [107]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [109]:
np.stack((a,b))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [114]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [112]:
np.dstack((a,b))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [113]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [115]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [130]:
np.ones((1,3))

array([[1., 1., 1.]])

In [137]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
np.eye(6,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
np.array_split(a,2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [15]:
np.random.randint((10))

0

In [18]:
np.random.random((2))

array([0.01519039, 0.97832322])

In [20]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [23]:
np.full(5,0)

array([0, 0, 0, 0, 0])

In [67]:
np.full((4,4),12)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [71]:
np.full((4,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [79]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [94]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [123]:
a=np.array([1,2,34,5,3,2,1,6,9,9])
a

array([ 1,  2, 34,  5,  3,  2,  1,  6,  9,  9])

In [104]:
np.unique(a)

array([ 1,  2,  3,  5,  6,  9, 34])

In [125]:
x = np.diag([2,4,6,8])
x

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [126]:
np.arange(12,40)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [127]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
np.flip(a)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [134]:
a=np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [137]:
a[5]=9
a

array([0., 0., 0., 0., 0., 9.])

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
b=a.astype((float))

In [11]:
b

array([1., 2., 3., 4., 5.])

In [15]:
a=np.array([1,2,3,4,5])
b=np.array([1,3,8,6,7])


In [19]:
print(np. intersect1d(a,b))

[1 3]


In [20]:
a=np.array([1,-5,-6,3,-5,8])
a

array([ 1, -5, -6,  3, -5,  8])

In [22]:
a[a < 0] = 0
a

array([1, 0, 0, 3, 0, 8])

In [18]:
a=np.array([10,5,10,20,7,8,10,11,12])
b=10
result=np.sum(np.char.count(np.char.mod("%d",a),str(b)))
result

3